book_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'))

]

catalog/urls.py
from django.urls import path
from .views import BookListView, BookCreateView, BookUpdateView , RequestListView

app_name = 'catalog'

urlpatterns = [
    path('books', BookListView.as_view(), name='book_list'),
    path('books/add_book', BookCreateView.as_view(), name='add_book'),
    path('books/<int:pk>/edit/', BookUpdateView.as_view(), name='edit_book'),
    path('requests', RequestListView.as_view(), name='request_list')

]

catalog/models.py
from django.db import models
from django.utils import timezone
from isbn_field import ISBNField
# Create your models here.
from simple_history.models import HistoricalRecords


class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    def __str__(self):
        return '{0} {1}'.format(self.last_name, self.first_name)

    class Meta:
        db_table = 'author'
        ordering = ['last_name', 'first_name']


class Book(models.Model):
    isbn = ISBNField(primary_key=True)
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    publish_date = models.DateField(default=timezone.now)
    history = HistoricalRecords()

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'book'

catalog/forms.py
from django.forms import ModelForm
from .models import Book
from django import forms
from suit.widgets import SuitDateWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class BookForm(ModelForm):
    publish_date = forms.DateField(widget=SuitDateWidget)

    class Meta:
        model = Book
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save book'))

catalog/views.py
from .models import Book
from django.views.generic import ListView, CreateView, UpdateView
from .forms import BookForm
from django.urls import reverse
from django.shortcuts import redirect
from request.models import Request


class BookListView(ListView):
    model = Book
    template_name = 'catalog/book_list.html'
    context_object_name = 'books'
    paginate_by = 6

    def get_ordering(self):
        ordering = self.request.GET.get('ordering')
        if ordering not in ['publish_date', '-publish_date']:
            ordering = '-publish_date'
        return ordering


class BookCreateView(CreateView):
    model = Book
    template_name = 'catalog/book_form.html'
    form_class = BookForm

    def get_success_url(self):
        return reverse('catalog:book_list')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:

            return redirect('catalog:book_list')
        return super(BookCreateView, self).dispatch(request,
            *args, **kwargs)


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'catalog/book_form.html'

    def get_success_url(self):
        return reverse('catalog:book_list')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:

            return redirect('catalog:book_list')
        return super(BookUpdateView, self).dispatch(request,
            *args, **kwargs)


class RequestListView(ListView):
    model = Request
    template_name = 'catalog/request_list.html'
    context_object_name = 'requests'
    queryset = Request.objects.all().order_by('-time')[:10]

catalog/templates/catalog/base.html
{% block head %}
{% load static%}



<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% endblock %}

{% block content %}
<body>
    {% block header %}

  <div id="wrapper" class="animate">
    <nav class="navbar header-top fixed-top navbar-expand-lg  navbar-dark bg-dark">

      <a class="navbar-brand" href="{% url 'catalog:book_list'%}">HOME</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">

        <ul class="navbar-nav ml-md-auto d-md-flex">
        {% if user.is_authenticated and user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalog:add_book' %}">Add book</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin Panel</a>
          </li>
            {% endif %}
        </ul>
      </div>
    </nav>

    {% endblock header %}

    {% block page %}
    {% endblock page %}
  </div>
</body>

{% endblock content %}
{% block footer %}
{% load copyrighttags %}
<div class="footer-bottom">
<div class="container">
							<div class="copyright-text">
								<p>CopyRight © {% getCopyrightYears %} Digital All Rights Reserved</p>
							</div>

				</div>
</div>

{% endblock footer%}

catalog/templates/catalog/book_form.html
{% extends 'catalog/base.html' %}


    {% block page %}
      {% load crispy_forms_tags %}
    <h1 align="center"> Write information to the form</h1>
 <div class="container">
      <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
  </form>

    {% endblock page %}

catalog/templates/catalog/book_list.html
{% extends 'catalog/base.html' %}

    {% block page %}

      {% load templatehelpers %}
{% load bootstrap4 %}
{% bootstrap_css %}
      <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Publish date:
  </button>
              {% with params=request.GET.urlencode %}
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% relative_url 'publish_date' 'ordering' params %}">ASC</a>
    <a class="dropdown-item" href="{% relative_url '-publish_date' 'ordering' params %}">DESC</a>
  </div>
           {% endwith %}
</div>




                     <div class="container">
        <div class="row">

        {% if books %}
        {% for book in books %}
            <div class="col-md-4">
                <div class="card-box">
                    <div class="card-title">
                        <h2>{{book.title}}</h2>
                        <p>Author: {{book.author}} </p>
                        <p>ISBN: {{book.isbn}} </p>
                        <p>Price: {{book.price}} $</p>
                        <p>Publish date: {{book.publish_date}} </p>
                    </div>
                    <div class="card-link">
                        <a href="" class="c-link">Learn More
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}

        </div>
<div>
        {% bootstrap_pagination page_obj %}
</div>
    </div>
  </div>

    {% endblock page %}

catalog/templates/catalog/request_list.html
{% extends 'catalog/base.html' %}


         {% block page %}

      <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Response</th>
      <th scope="col">Method</th>
      <th scope="col">Path</th>
      <th scope="col">Time</th>
      <th scope="col">Is secure</th>
      <th scope="col">Is ajax</th>
      <th scope="col">IP</th>
      <th scope="col">User</th>
      <th scope="col">referer</th>
      <th scope="col">User agent</th>
      <th scope="col">Language</th>
    </tr>
  </thead>
  <tbody>
  {% for request in requests %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{request.response}}</td>
      <td>{{request.method}}</td>
      <td>{{request.path}}</td>
      <td>{{request.time}}</td>
      <td>{{request.is_secure}}</td>
      <td>{{request.is_ajax}}</td>
      <td>{{request.ip}}</td>
      <td>{{request.user}}</td>
      <td>{{request.referer}}</td>
      <td>{{request.user_agent}}</td>
      <td>{{request.language}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

    {% endblock page %}